# -*- coding: utf-8 -*-

PRODUCT_URL = 'http://www.systembolaget.se/api/assortment/products/xml'
STORE_URL = 'http://www.systembolaget.se/api/assortment/stores/xml'
STORE_PRODUCT_URL = 'http://www.systembolaget.se/api/assortment/stock/xml'
SB_ARTICLE_BASE_URL = 'http://www.systembolaget.se/dryck'
ARTICLE_URI_KEY = {
	u'Alkoholfritt' : 'alkoholfritt', 
	u'Lik\u00f6r' : 'sprit', 
	u'Ros\u00e9' : 'rosevin', 
	u'Sake' : 'aperitif-dessert', 
	u'Calvados' : 'sprit', 
	u'Fruktvin' : 'aperitif-dessert', 
	u'Aniskryddad sprit' : 'sprit', 
	u'Gin' : 'sprit', 
	u'Sherry' : 'aperitif-dessert', 
	u'Bitter' : 'sprit', 
	u'R\u00f6tt vin' : 'roda-viner', 
	u'Mj\u00f6d' : 'aperitif-dessert', 
	u'Brandy och Vinsprit' : 'sprit', 
	u'Vermouth' : 'sprit', 
	u'Blanddrycker' : 'cider-och-blanddrycker', 
	u'Grappa och Marc' : 'sprit', 
	u'\u00d6vrigt starkvin' : 'aperitif-dessert', 
	u'Kryddad sprit' : 'sprit', 
	u'Whisky' : 'sprit', 
	u'Vin av flera typer' : 'aperitif-dessert', 
	u'Tequila och Mezcal' : 'sprit', 
	u'R\u00f6da' : 'roda-viner', 
	u'Okryddad sprit' : 'sprit', 
	u'Ros\u00e9vin' : 'rosevin', 
	u'Cider' : 'cider-och-blanddrycker', 
	u'Smaksatt sprit' : 'sprit', 
	u'Portvin' : 'aperitif-dessert', 
	u'Vita' : 'vita-viner', 
	u'Punsch' : 'sprit', 
	u'Armagnac' : 'sprit', 
	u'Aperitif' : 'aperitif-dessert', 
	u'Drinkar och Cocktails' : 'sprit', 
	u'Mousserande vin' : 'mousserande-viner', 
	u'Vitt vin' : 'vita-viner', 
	u'Rom' : 'sprit', 
	u'Montilla' : 'aperitif-dessert', 
	u'\u00d6l' : 'ol', 
	u'Genever' : 'sprit', 
	u'Sprit av frukt' : 'sprit', 
	u'Cognac' : 'sprit', 
	u'Madeira' : 'aperitif-dessert', 
	u'Smaksatt vin' : 'aperitif-dessert', 
	u'Lik\u00f6r, Choklad-, kaffe- och n\u00f6tter' : 'sprit', 
	u'\u00d6vrig sprit' : 'sprit', 
	u'Gl\u00f6gg och Gl\u00fchwein' : 'aperitif-dessert'
}